#!/bin/sh
ORG_PWD=`pwd`
SCRIPTPATH="$( cd "$( dirname "$0" )" && pwd )"

die () {
    echo >&2 "$@"
    echo 
    echo Please enter a valid plugin name directory, it must be one of these:
    find $SCRIPTPATH/../plugins/. -maxdepth 1 -type d | grep -o -E '\./[^/]*$' | grep -o -E '[^/]*$'

    exit 1
}

run_php () {
  php $1 > ${1}.new
  mv ${1}.new $1
}


compress_js () {
#  extension="${1##*.}"
  java -jar  $SCRIPTPATH/yuicompressor-2.4.6.jar --type js -o ${1}.new $1
  mv ${1}.new $1
}

compress_css () {
  

  dirname="${1%/*}"
 
  grep -E '@import\s+url.*$' $1 | while read line;
  do
    
    basename=`echo $line | grep -o -E '[^"]+.css'`
    path="$dirname/$basename"

    safe_line=`echo $line | sed "s/\"/\\\\\"/"`
    sed -i -e s/"$safe_line"//ig $1

    cat $path >> ${1}.new
    echo "\n" >> ${1}.new
  done

  cat $1 >> ${1}.new

  java -jar $SCRIPTPATH/yuicompressor-2.4.6.jar --type css -o $1 ${1}.new
  rm ${1}.new
}


[ "$#" -eq 1 ] || die "1 argument required, $# provided"

while read dir
do
    [ -d "$dir" ] || die "Directory $dir does not exist"

    revision=`git describe --always HEAD`

    new_dir="${dir}_rev#${revision}"
    cp -a $dir $new_dir

    echo "Compressing Javascript - Running any PHP files"
    for jsfile in `find ${new_dir}/js/*php -type f`; do
      echo $jsfile
      run_php $jsfile
    done

    echo 
    echo "Compressing Javascript - Running YUI compressor"
    for jsfile in `find ${new_dir}/js/ -type f`; do
      echo $jsfile
      compress_js $jsfile
    done

    echo 
    echo "Compressing CSS"
    for cssfile in `find ${new_dir}/css/ -type f`; do
      echo $cssfile
      compress_css $cssfile
    done

    #zip command references the working directory for it's directory structure
    cd $SCRIPTPATH/../plugins/
    #get the original foldername
    zipfile=`basename $dir`
    
    zip -q -r ${ORG_PWD}/${zipfile}_rev\#${revision} `basename $new_dir`
    rm -Rf $new_dir

    cd $ORG_PWD

done <<EOF
$SCRIPTPATH/../plugins/$1
EOF
